services:
  alpha:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - APP_NAME=Alpha
    depends_on:
      - redis
    deploy:
      replicas: 4
  beta:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - APP_NAME=Beta
    depends_on:
      - redis
      - alpha
    deploy:
      replicas: 2
    ports:
      - 8080:8080
  redis:
    image: redis
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - beta
    ports:
      - 9003:8080
    deploy:
      replicas: 0
